name: 'Terraform GitHub Actions'
defaults:
  run:
    working-directory: "lecture7"
on:
  - pull_request
  - push
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

 
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} 
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }} 
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      # - name: 'Checkout'
      - uses: actions/checkout@master
      - name: 'Terraform Init'
        # uses: hashicorp/terraform-github-actions@master
        id: init
        run: terraform init
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Terraform Validate
        id: validate
        run: terraform validate 

      - name: Terraform Plan
        id: plan
        run: terraform plan 
        continue-on-error: true    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
